FROM python:3.9.6

ENV PYTHONUNBUFFERED 1

RUN apt-get update

RUN mkdir /code

WORKDIR /code

ADD . /code/

RUN pip install --upgrade pip && \ 
    pip install poetry && \
    poetry install

EXPOSE 8080